version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/PREDICTIVE_MAINTENANCE
      - /PREDICTIVE_MAINTENANCE/data
    working_dir: /PREDICTIVE_MAINTENANCE
    ports:
      - "8888:8888"  # For Jupyter if needed
    environment:
      - PYTHONPATH=/PREDICTIVE_MAINTENANCE